---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-superuser
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-pg-superuser
    template:
      engineVersion: v2
      data:
        username: "{{ .username | b64enc }}"
        password: "{{ .password | b64enc }}"
  dataFrom:
    - extract:
        key: immich-pg-superuser
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-pg-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .POSTGRES_USER | b64enc }}"
        password: "{{ .POSTGRES_PASS | b64enc }}"
        aws-access-key-id: "{{ .ACCESS_KEY_ID }}"
        aws-secret-access-key: "{{ .SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: aws
