---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app freshrss
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      freshrss:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: freshrss-secret
        containers:
          app:
            image:
              repository: freshrss/freshrss
              tag: 1.26.0@sha256:d18055cc1c2fa807f118accb4ba74f435d381daf96130f87b17d9d9d1d169341
            env:
              TZ: ${TIMEZONE}
              CRON_MIN: 18,48
              DOMAIN: "https://freshrss.${SECRET_DOMAIN}/"
              OIDC_ENABLED: 1
              OIDC_PROVIDER_METADATA_URL: https://auth.${SECRET_DOMAIN}/application/o/freshrss/.well-known/openid-configuration
              OIDC_REMOTE_USER_CLAIM: preferred_username
              OIDC_SCOPES: openid groups email profile
              OIDC_X_FORWARDED_HEADERS: X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto
            envFrom: *envFrom
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:rss
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /var/www/FreshRSS/data
