---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: readarr-secret
    template:
      data:
        # App
        READARR__API_KEY: "{{ .READARR_API_KEY }}"
        READARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        READARR__POSTGRES_PORT: "5432"
        READARR__POSTGRES_USER: &dbUser "{{ .READARR__POSTGRES_USER }}"
        READARR__POSTGRES_PASSWORD: &dbPass "{{ .READARR__POSTGRES_PASSWORD }}"
        READARR__POSTGRES_MAIN_DB: radarr_main
        READARR__POSTGRES_LOG_DB: readarr_log
        READARR__POSTGRES_CACHE_DB: readarr_cache
        # Postgres Init
        INIT_POSTGRES_DBNAME: radarr_main readarr_log readarr_cache
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: readarr
