# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app readarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      readarr:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: radarr-secret
        containers:
          app:
            image:
              repository: ghcr.io/joryirving/readarr-develop
              tag: 0.3.31.2578@sha256:2459944870fd18fe92b997d616eebd921abf08ad177d3a23f904640bd2aa1a76
            env:
              TZ: ${TIMEZONE}
              READARR__INSTANCE_NAME: Readarr
              READARR__PORT: &port 8787
              READARR__LOG_LEVEL: info
              READARR__APP__THEME: dark
              READARR__AUTH__METHOD: External
              READARR__AUTH__REQUIRED: DisabledForLocalAddresses
              READARR__LOG__DBENABLED: "False"
              READARR__LOG__LEVEL: info
            envFrom: *envFrom
            resources:
              requests:
                cpu: 15m
                memory: 160M
              limits:
                memory: 330M
    defaultPodOptions:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        hosts:
        - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              identifier: app
              port: http
    persistence:
      config:
        enabled: true
        existingClaim: readarr-config
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
      downloads:
        enabled: true
        existingClaim: sabnzbd-downloads
        globalMounts:
          - path: /mnt/storage/downloads
      data:
        enabled: true
        existingClaim: komga-assets
        globalMounts:
        - path: /data
