---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${VOLSYNC_CLAIM:-${APP}}"
spec:
  accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY}"
  storageClassName: "${VOLSYNC_STORAGECLASS:-longhorn}"
