apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:HsdUxOa+st+ltfpm1I/1R8sI1jHG8F4o2KdIe//QpFigrmnm,iv:9kXL8gM00CfMllliFP6yy/hh4+DtRiMGgbNR32m0ayw=,tag:f0Rax/9Ds9sDojOlVYQF1Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:LUyXkvO40qycv5xpw+NPAMiklo1JxZNqEIvMsp5DYl3sMkgaYsbqhGB2eCMvN9tM+i/xcGV8ELfwWFgcvAFWv8lu+fLETaE+q4vCcvTbS9OCiHxdeyrKnZwTPM0wmWd71Yg6yr79hdonJ258LDK3oOOMGF5yvaTPDQpyrDVWUd2vigS/sEVFzCSPyyb6LrbFsiEKUXSaKA8Oo147YtP+7+bDkjfkusI/k1ZckiGUIw==,iv:EN6Nmc2kdB9ajWH4/PlRv1HdVeis1XdURiU5BZ/IaAk=,tag:35P/VOGMzb8YkrIScye+yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZjlQeHUrODRleWVEaW5r
            cWpEbWVSN3J3Q2pRMXd1VkhGcHlmczZxeldZCm5HVnAxOVNacWczbmUvOExFOGtn
            V29EQWFzUUdJR2NlZEhQVTlyQk04NkEKLS0tIG1aWDk4SDVZWDdGVmVlOW5FM09F
            bjZ1cUlEQXkxdVBOMEh1QjN2anVhckUKv0fmwBvl4f+0jTvlBPRliamPpiHZLHCX
            kjdc8bI294ENmJiQCUnyTybuslvrGqhZSHa2G5y9iczZ7fO+NFBW2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T22:31:44Z"
    mac: ENC[AES256_GCM,data:II20f/4hfvQ+TmQGgiZY+7R7yJaSDRRjG1+grMCyfH2M0NxKNF32c504hkSqjJSC36hu5FAgpPa2/w3qUx7U5lWMSQGnBp+NcbcC0TgJKudWC66aBPcZCysa5Yquj35iU3RCYrS2OCCHAjatj4s1VaMWElCn5tlmduqHLybErdg=,iv:v99RKR+yJvk54WTKIUrfeSC8dWqBsUiOggG/LfDQUUA=,tag:xegEcibmmICMyDEcZlkCiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
