apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:BzHC4scJbkZZgChFr0PVBz5SGGqjogyXM0GujeThq4Qm+v9t,iv:v9B6eVc2P5Q67Pl3DOZVKKnaLli685bEU4wYIdFD1nM=,tag:LxCeiM98Q5eKPtFKlqC9GA==,type:str]
    credentials.json: ENC[AES256_GCM,data:ar+Gg7ptBlWWSgm2dqRkTAC7AtRVVqLsQqyVWKj7SxkafjauxH6OLKlAeE7XHkjvfGr++ZmvQ4q4y1mxlCYHffl+r0TTyPGpM1F7Ufb+Xe28AS8dgcxM3HZwL7duiP9HBp717uqtu+JhSsUrDjCap8PO5wZUnflH59YFbd8kfi/0dqNdRrifQIv+3oIZSqMwo7nt7eoGSY475OprrpKPIpyAvu34CA7bkKJAmWQ7Yg==,iv:3h9cM32Gw1qIegiPSQYKcGReTTnWTj4eKpTrEZJklA8=,tag:QUtUNxTttMBMGGv4GdfTXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWERrWlpFdkcramo0Qit6
            MU5FdllOUWZXdnFvRjNPQThVS3dJRU14QlFvCjhYWjNxNWRncXRLNFZsNHI5NzNn
            eWNub1lJYzgyTW5ZcHp6ZzlEWTRrbkkKLS0tIHBUTG9nN2ZONWxDcUROVWttMHov
            c2RvVEduNEZsVy90VjgrK1JpZVRJbWMKyrfDJwIrJto9OK7HluI2qquyxRgOysIk
            pO+Ni/JVnuoHUernrNgYk1dZGxh0PaHFLqivvi3s3FNAgO0nV8ZOuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T22:11:10Z"
    mac: ENC[AES256_GCM,data:5s9R/teTjs0mMw/hLIZKP3UMgDOghCQ+gKnbK76fFWqMvxw6uUnJhtSQxn0Xscm5af+4SJksQOTQ66htkULYdGqSKLrabeZuvss1N03SWCCYR03kWqMjaOMiEYHkvUFgcegyUoEI8sdkSeSXo13aNtEjimXsCjONI82JiFu+muM=,iv:FXPTaEE6HVw00RzyESxCHVUtWaNSi55jEYs6ZPGRcxg=,tag:rv25CG9B+5zVx+WVD9PF9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
