---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-authentik
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security/authentik/app
  targetNamespace: security
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname authentik
  prune: true
  wait: false
  interval: 10m
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: dragonfly-cluster
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: auth.${SECRET_DOMAIN}
