komga:
  eventListener:
    enabled: true # if disabled will not connect to komga and won't pick up newly added entries
    libraries: [ ]  # listen to all events if empty
  notifications:
    libraries: [ ]  # Will send notifications if any notification source is enabled. If empty will send notifications for all libraries
  metadataUpdate:
    default:
      libraryType: "COMIC"
      updateModes: [ API ] # can use multiple options at once. available options are API, COMIC_INFO
      aggregate: true # if enabled will search and aggregate metadata from all configured providers
      mergeTags: true # if true and aggregate is enabled will merge tags from all providers
      mergeGenres: true # if true and aggregate is enabled will merge genres from all providers
      bookCovers: true # update book thumbnails
      seriesCovers: true # update series thumbnails
      postProcessing:
        seriesTitle: true # update series title
        seriesTitleLanguage: "en" # series title update language
        alternativeSeriesTitles: false # use other title types as alternative title option
        alternativeSeriesTitleLanguages: # alternative title languages
          - "en"
          - "ja"
          - "ja-ro"
        orderBooks: true # will order books using parsed volume or chapter number
        scoreTag: true # adds score tag of format "score: 8" only uses integer part of rating. Can be used in search using query: tag:"score: 8" in komga
        readingDirectionValue: # override reading direction for all series. should be one of these: LEFT_TO_RIGHT, RIGHT_TO_LEFT, VERTICAL, WEBTOON
        languageValue: # set default language for series. Must use BCP 47 format e.g. "en"

database:
  file: ./database.sqlite # database file location.

metadataProviders:
  defaultProviders:
    nautiljon:
      priority: 30
      enabled: false
    kodansha:
      priority: 60
      enabled: false
    viz:
      priority: 70
      enabled: false
    bookWalker:
      priority: 80
      enabled: false
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA.
    mangaDex:
      priority: 90
      enabled: false
