apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:cAW2KrHaNCjiZelgfLxoCXrX5F2+aJupvDz7b6X+Ij7txuQtaUTckg==,iv:8/bNoU8WVR7nsWXEBq1vGSswFnm8QSZerE5ogj6EpFA=,tag:G/sFTInHLRMonxvPpvZy1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUzZVQkEvK2VjaWc0eXgr
            RDBmZzlTN2hhL0FLUkd5bmc2R0F5Zmk5MkVnCkRsTWtjTmcrTE9YUG1KR0ZqdFVX
            dE9YU1dPWGJnUUlBOTYrUWx6S2xCUDQKLS0tIGpaeExHSU9weUpmQldUdkR3cU10
            VE5FN3czZ28xb2pjeitxcVYrYXFQRlUK5Ly5cqOrsV9ZSmCrlzLulqSIiEKuQQRO
            eCoKlc8XAmVhGRZlvDjZkmLAl/oHbvQU/WORtzfw4MdtrFSbTJYM+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T01:24:07Z"
    mac: ENC[AES256_GCM,data:XM4Ly8S55Ff7mAlwxS7LpY0co9S8gDQIzoqDGL1SZ/NOptXqbwLumpWCBHGWHzM2BjT2CkZVXDKpip7yAGhjJOjYgG+J4mKMrm38eBoGB8GmkCEgg+GOHhv4dOBnRUWgSomC7hZ1URu25VGmTcxE5yie57Jcmi8m2CmvFOcPsyw=,iv:uAtEFug04lP6CxNygkD7zoWTdbGji7maLe8TKbQ1CaE=,tag:bpCCzGloP1tdrExk0JdKeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
