apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:sDfkZBee8RYNJDbz9UI4II7e67DxeTGk9wYT0R21aTPY35Qbgo6dJQ==,iv:k254BA8PHNKotukHpF4oq7IqLBbTjU2GBTa1faY/a2w=,tag:Hm4B9+BG1fBtopYGRhk0AQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKd1dnbjZjU2tJNjZibS9Z
            QTNidHFwNVZJdXRLVm94SlBaZ21NYWRMU1ZNCkRBSzJCOXF6UE4xNzc0SjluM1gz
            SHZJZlpCbzJPNUUrZ0FXN2cwMng4OUUKLS0tIEY0L1Rzc3dsVGs5dzNhZXUvRjda
            UUp6Rmo1QTFIckIyZDZDeEJ4R2FXNHcK2hTY88GkchAY90yA8lyer6FiZVorTRtK
            7w+Fb6zr2RthukD6uE7DZxO+6029GIqZ9LF3sClci6vBzy0k72QFwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T02:37:29Z"
    mac: ENC[AES256_GCM,data:N59W+GJf37ZqKf+K046smaEAg+n0pz8KIWaVrfz6wVJyrGQtQOgfyGSXQ//Zkt1SVcEJpbDxAHpC09Wbl8e+js8jbRqowdxHLeqeaHMYoqK2C1QGOpfNdIiXcwsTRP+kCsZe7a8v6abIq+/MRcOqT3n4SkniReKI+H3vPpyiZNo=,iv:ow3m/OuQs0GNsnwkv53eyNUmbQx1gW9P5Zk6b4KPtmc=,tag:5Nv/ovipzVHvfxqEfBIqww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
