apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:QQkyGU+W5gcwOgXLVQarh9jK+ATDZaXlnKhjmy30IlNm0DW1wgHDMA==,iv:LUnhbrg09X/qB368U4R6y3frl0GzNN83LNKQWaQEMIY=,tag:US97F/BEGVIsJliN8t6A9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MlpnTHZzZTJJTkJLMG4w
            ZkVCdlJtMnBhQ2RhTlVMNlNtRGNEM3pxR1hVCkJRQUNtRmluTDJiKzM1TkdZekpH
            bWpUeGdPUEtEVVNXdXdjZUZmNlFWZ3cKLS0tIFhFQUVaVnd2QU1La0RTdVlTTkJH
            a3BHYlZ3bFJFeUtHbWVyZXRLVHk3bG8KMM+ASxkjaTyY/tnYxt/Kc1EWr3CLKBz7
            QI1NIo5J6/gWtT8cTVanU5b01JZXB+7cvtofMxjNEcnVWFpR5wUhEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T02:42:20Z"
    mac: ENC[AES256_GCM,data:umYNWR013PQhpsh2ggnZ748IQtSZbVjeisMvpw3ALl9T6U26uZ3U94NDBwSVHclP6frdKatAJ2ujPcrOu76q4h5nT8J023nckHNZ77xiBPueno0w4oVUuk0/ShhgcLOIyLpX+x+0XWOUVAihnSwzRJt6wfPRocQVQOYkomfD6ic=,iv:DvwAr8U4KWbmDkeKbu+klBNExs5T3csLUL8J9Q527A4=,tag:6ePKX0NeLqnkW9I+yNI0fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
