apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Mbnzlj0+x8v9WstJvZuzxHqH0Pzc3dcsAiDChfiAAXM9fPBMj53KhQ==,iv:cIjLa2JcflR8z2qrtC1EEC/CYUd6qr4rj0vB76wDSGA=,tag:0BghHcHqaLbS5wnQjfoilA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOHkydXVHVkhWaGJqQkRE
            eXZpV28wbUJVTU9tcUsyZWlrY1Frb28zNWkwCmJjQWtoUlcweTJhS3FDOVI1bENq
            TVBFOXNxWE9Kaml3YVAzZ21HbDRhbFkKLS0tIFJxcTFWNHc1WHdZVlNGV0d5VkVk
            TDNWUDk3NnNjRitkeFQ0enJ5VHg5dGMKhP6sP4fAgxmsSPprhuqam6R40e7sli9h
            n8eFLMTSq7z0bLVytROeRH5ZyXabCJtSUcShdU6Rjy1E2lzK8LK9ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T19:32:13Z"
    mac: ENC[AES256_GCM,data:4gdrS/Ijegt0Gyo4FxN/FG6BRiXqr2nF+qcLLwEkdLLQy0rTQ2DB/QZ4sv1j5f635FTcEFRhljmwQWvSAUZ9uEbD0A14tVDmOv9A6iqEspIf6oMF5l9ReXw5jvAMqNIfYN4aF21C5ACHqyWw1fRJ9923v+ReTCywfkPjSG9gMVc=,iv:6bbyWDqKE/Cu/ZpHrOzI+WQnTPs/E1eVAM1SJ3BaZVM=,tag:QQpIpbNu2FdJ9g+matUfHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
