---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./atuin/ks.yaml
  - ./freshrss/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./sonarr/ks.yaml
  - ./unifi/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./wallabag/ks.yaml
