---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duketogo-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-reliable
