---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-snmp-exporter-cyberpower-ups
  namespace: flux-system
spec:
  targetNamespace: observability
  path: ./kubernetes/apps/observability/exporters/snmp-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
