apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:OG7CuiEOeZbyVfUQ36TDGzUl6tnauaE55fjrZltvN6mxx96fUWR1zN9eaoSNj2y0gH7vrFgAzXIrwpV8naLofiwfB/8I0qE0+U1U0iGm37QYhcfZPAU8aOX4rg8/Dg==,iv:0IemDYJE2v4gcKH78s4uDO4hvm1iYAQtQ0hW6IkiM24=,tag:0KJE6kM+Jw0naNC5Vlxn4Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:K4r96Se+RbjmHv4=,iv:YSZKL4R60kezx6b5RZqKKWfWVQpeF9X1cPEvnzasTOA=,tag:uHCMGTZNUUhabcw1bm595w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:aL5v+JcTi8B1AsGM3LnS,iv:WkYL+gCtpqw6XekvIJcXeq4sIX4Axojym3fv4MHcJ6c=,tag:tezYHFAJekrYXPJd/cBytQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:z4ylIpY+LGpjXu5FSP6gnPDfJoyAnxRpYnt/KXmQ5JRCkN2s,iv:QM9OtDbBL4hv//Lg0alR43CqzNuPvaWkw36m+gdD/Wo=,tag:0dsJswj4bSiSye/kWrcjIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVjE3a0RucDZBd3NiLzIr
            cHRMaG9RWk9nYlJkK0FlU2diWFJoZkg4Q2lJCnlaNWdGRUV2eTBvRVZxbDR2Y0Ni
            dFpNZTR0TlQ5U0hGS2ttZDUyclJxV0UKLS0tIG1uaUNFdUtzRGRLV3VFaEw5S3ls
            cVI0S3dEVzJOcEh6MUppZ2xpOS83TkkK2xHdmlWWSSgvBJtaLvu7cEln6NfwaDxM
            NNUUHElTf8T/ADWj+XGFzLX1EOR7mhEqEuj3h89drawuBeDspsyieg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T22:45:16Z"
    mac: ENC[AES256_GCM,data:tW8qkUQrsm9T1IlpfBxuzfKtdMKSFWhlyVtTN1pe4SfdHAWetpAuM+zYxtYaEpBFjfmA4eBLbHnUjKR9pepA4HmB6rnA0eervLiBCZdI19ILwFAl1quXYz/4d/5PGOLYdGh5TbzEOHmQXZivExkSWZsZQDjO3dO38TMMVNFUbts=,iv:pHo/7x12ks560cEGAXdbni6u/RIfmS/FPn8/2senEBU=,tag:NMZeSbjzxCwsifp7pRKOqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
