apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:nKvY065/pprD1Bw=,iv:iWxAIvozaenG5Z8oBt5fjALB8/WXxODQDkkBp9KdZDM=,tag:BEbDAb8cJOR9DgZ33SMfKg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:hxHIw+kK2clWGDxsMd7M,iv:lQwqIeiV+kuViMwvzb+ZTGUElvMV6VBv12lO/YCztQc=,tag:ExAAJ4ZW9ZJiKUiTKaBP9w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:mNSfdYuIDKcTYoNZzM5edm9pd4geV7LNKgvgVx6/zSjtl8TW,iv:DGIKDFlvHP1HBvOZ9zaqWnm2mj/KwIQJStfg0Y38gPs=,tag:LmhADVBgwS7igjtWkulgRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWkUyM0xNSlRTUjFUTHZE
            Z0M2RUJBekYzTzBvRks3aXJRTEs5WGNaVHpZCkVDUEpodzFSUVU4RS9Kb0Uyblk5
            aTZMYTlOWnN6Lzc3NWc0L0paeDhFdUkKLS0tIHdUMG0yN1g5NGI4S3N5NWZGQW9s
            LzVIQlE4M1NTWnJVZlpLMXJiSW9IZGMKJTMOZgU8+viCDsCZeQddYprLTVZW6eFz
            4g543t70MU8E/hJYnf4Hkqva83j0ZEin496K02z27HwzhFD1BhV2Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T03:50:59Z"
    mac: ENC[AES256_GCM,data:7uNlppTo8Rc3nKcOdEbHtgN6gnwtba+2HdckltH1PDzjM8dOxJMl4o2HiASOuIzL0q3UflHW501+3tv6bk9nEzpJg4J6Ep6Ab9QUb6tK/c+qewN4a9DDShLwYr9hJe5SB9H1/HAgJ1rPONuHPDjUcGUA8Ohm/endF0uc1tvZhaA=,iv:QH/pHKySqRaqvw1ugKiu6F/IRW6wtkFOqxHU5GTOpnk=,tag:j4mTdT368gjAV/yX8nCCzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
