apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WBOCHccyKIC/uv8=,iv:AHsLSIyWJ7gWHybHEG+OYWy/RRRJTKjexsWDZHw+KjM=,tag:LfWbK1cYOtdVSOupN7qaAw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:AovZIyEaZEmeYnjW7gNZ,iv:jPxnYtxIsu6fRW3LcstJNJk+W5TPLJByGRa4G7JnB4E=,tag:nXiQiy+olUm9wejEYLURRg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KL02xwZ94kdC/Zo+N2FmuT0fADS46tVhp3d9nHjkNLaAbVyU,iv:Nngl2FjZbAtjxHqb1lfk7U5vEcKUv4yUG1qttnTeBpA=,tag:oaxHrPsWr+sV5G3LvyjIbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUEFLN1drV2NSai81K0Rs
            NDJ1SjMxdjY4TWVnd00zUDBPUmtzbFovRG0wCmhuSG5FWVhMWG5Ldy96ZVhsbTlO
            L0lhMXBVRHBoc1JoL0FaUGtXRkIweFEKLS0tIHpoWkQvcXdQQ1MrTDcyZVdMU0hU
            cWtvMzE1aWJ2U0w5SEZ0SGVnTVBuUWMK3rUU5wGqFEMPCD82CRN8AiY5whEjb2K2
            6lp6SvwUrUWuWYifokL9swf8mpQSrWNga+YtiGWief+Asv5jkBrGrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T22:18:42Z"
    mac: ENC[AES256_GCM,data:TolkWBVILJ7m/3B9I+L6E6n0FKioLSPZtFpvkkuCjOzLawxAS4OJnxZ83tY3LY478PtPGUNFcQuqGBdNjCxuyrBcsi2f/ZPEM+EDbbW9b3mBuOyG8bBFxEOsNwsZQRf+7yIXZ2NoZxfeImP/KU6Ok64ASgdftvmwp/kKsGnic9o=,iv:v/XnGy8fq/gTeDe4aGR+Inklt9TXDu5J42ETOX8alxE=,tag:uW5btecMV1ZQIJWp23vJtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
