apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Fnf0KyU6T+k8xeYWGyJqqBEAzxIQKSt4Z5UQGTEolwBedvIEJd/01LZLTcOMTTL1+a5Oq08pQhad4XTb5vdD6V0viH3JrXFV2XcTCZASsDlXQsAK0rscnXScbsoCeA==,iv:8TsqH6+ISaF6m0RUuXk1rK8gs7OfPsGav8QA3VKD1ao=,tag:4yJFsIJy8jTu/XuMhK19mA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:/bRS1OGq5sBDhP8=,iv:1rBJmEKemyQOotcWpBFPVVkG6aLDWQnQlg1VU1PURcE=,tag:7kEmRlE3YWSrojlKSZfXdA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:hW8dfdG6QxbF4FEtKaP9,iv:q06yKB0/UeD3fweYU7p7YnkI8VDmC+kDHj/lxMJiyzM=,tag:1lwaAK54UgDn7MjzlqWlbQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:s9wY9HW9Z3uP2n1QWSBhGjAy9gMYIGyCzyWuVr3Hsm8RiJiS,iv:54CGb/35EQimvjTR4za44do2Zrn2Pos9ZaAhli9jIUM=,tag:P0DXnxX2KFK5MV7mwjUj8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T2pWWmw3SU0weWRzRUl3
            ZWViWmVhbXVWdUpXL3d0d0NWbXdxVGZ2V1JjCjNvUmt3UTZQYXNON1NFbnhCS29v
            V1FLVE1ydm4rOEg2WGtvYlAzdm1CRk0KLS0tIERkQUMyaUhSVTlzT2oySnUwRXVr
            T0c2NmZxQlZPTkMxMzRub05CSzRidlUKqlvLtMKHz4GM9wJm5fbiMoUnG9aLAHAp
            mu8aN5uKqtZZ/Avnbqnb8fTFPrnisy83zxPAKRwKHSQEWzjBzKff3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T02:42:20Z"
    mac: ENC[AES256_GCM,data:kCHDrdexbKfQjmsxKlEbFJaT280W4ocUF5Ep8fuNENJA1w94NGpnhjHJs0dsMoNccwVQTCNOhVr5k/g7bvsm6C7fqRCUWdkcSjkC4tOyzkoOjEdXTz5ylCjZPMUvzwSFgqVhY1utew9oCSQX2tk3pgjWfJ72/WK8qduleNEnMK4=,iv:jF3n9mK2w7+kxNjCStemp6yZRTs6pdU6rNjxhQ13JQM=,tag:oYv/Foijj8hue+5+xBGtZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
