apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ydPw0wk2ZlMRW+8=,iv:5nW6ro2gtDRmYHqprwJ5OfUmh0ZsYMd4IwmwlAKlFLo=,tag:jcaxjUjL601ojr5kaY3NcQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:fwlfndnCrcvE7yuyOENI,iv:sxFbpuv7BSbk05XjjrNWsjLpYC6WxU8Yo4718OItOoI=,tag:3SyJVl8fho801wrMNnOSkw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ErBtJir6D24fI1lLVnn6YsuWuZZMinSn7B5n/zlLPonWPhrX,iv:ENOxHSndrfu0TXxXs2+bKI9ewG1VQyAjl6Ndf/MXUa4=,tag:U+FyXJCqmi18UhRpRUuTcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeXJISklMS3lwQVJ1bndC
            LzV6SG9wdVRSYU8yNWNHVkN5dnhoRnVqSmlRCmptQVVLSW9jNkVaRjV1MHUzNGJQ
            ZGtkekRPTjBNSHlwWGY0YUFYbWF4YWMKLS0tIEtBWWtNYzNXenlTTEdKOXphNktE
            RmllZ0d2TXBVS1o5OVd3SG9Hd2dTKzAKtSllOech2wkfMV/8W2QRCHpbdSqDsiG6
            Fgq+bv1iv222Z7Sz6opK4gLH2cy9XImr32PQ5+HEtiArN9RBEwf58w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T00:13:20Z"
    mac: ENC[AES256_GCM,data:mYZWqJmOtDVdOC6GFCdHZoS64GCktJSj4UXINXJEyfzdzRdGx1dNORCcWjBUvQNlEnAfTFT3b90Y+xTlVjjyjgy1/9D8FuqXUVwaZ+/iKshMaXMtp1kG8NxQ6l6D9p7yeB9tWCZqY3nsJ6DLHUs/eRBeBRL8rsuf2gZ8p29Y7WE=,iv:29TqE8Rqohl2ZX7AjEGZ4dwkUEhARhAg+mY3+y8v8KQ=,tag:wgPkXVT71shZ+ItqxV3fPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
