---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - "h4uno"
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 65542 # gladius:external-services

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.41.4.9463-630c9f557@sha256:a0dbab7e3f4ad3269ea1dfc502e6f5af73f7c89ed98fff093e5dab048d0d30e0
            env:
              TZ: America/Los_Angeles
              PLEX_ADVERTISE_URL: https://192.168.2.203:32400,https://plex.${SECRET_DOMAIN}:443
              PLEX_NO_AUTH_NETWORKS: 192.168.0.0/16
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
                memory: 9248M
              limits:
                gpu.intel.com/i915: 1
                memory: 9248M

    service:
      app:
        controller: plex
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.2.203
        ports:
          http:
            port: 32400

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        className: external
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: plex-config
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server
      plex-cache:
        existingClaim: plex-cache
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Cache
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Logs
      media-music:
        existingClaim: media-music
        globalMounts:
          - path: /data/media/Music
      media-video:
        existingClaim: media-video
        globalMounts:
          - path: /data/media/Video
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
