---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 550Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-video
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 450Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
