---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paste
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: bbangert/ofcode
              tag: 0.3
            resources:
              limits:
                cpu: 400m
                memory: 2048Mi
              requests:
                cpu: 20m
                memory: 40Mi
          redis:
            image:
              repository: redis
              tag: 5
            resources:
              limits:
                cpu: 20m
                memory: 2048Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
            targetPort: 6543
    persistence:
      redis-data:
        enabled: true
        existingClaim: *app
        advancedMounts:
          main:
            redis:
              - path: /data
                readOnly: false
