---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-reliable
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "480" # 8 hours in minutes
  dataLocality: "best-effort"
  replicaAutoBalance: "best-effort"
  recurringJobSelector: '[{"name": "daily-backup", "isGroup": true}]'
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "480" # 8 hours in minutes
  dataLocality: "strict-local"
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  # used for volsync to copy from.
  # we set this to 1 replica for faster restores from the snapclass
  dataLocality: disabled
  numberOfReplicas: "1"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
allowVolumeExpansion: true
volumeBindingMode: Immediate
metadata:
  name: longhorn-snapshot
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  # we set this to 2 replica for less copies of the cache, which can be blown away safely.
  dataLocality: disabled
  numberOfReplicas: "2"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
allowVolumeExpansion: true
volumeBindingMode: Immediate
metadata:
  name: longhorn-cache
