---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-reliable
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "480" # 8 hours in minutes
  dataLocality: "best-effort"
  replicaAutoBalance: "best-effort"
  recurringJobSelector:
    enable: true
    jobList: [{"name": "daily-backup", "isGroup": true}]
