apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:3FStpXC6CJITKe7P4Q3xgc39ooBpLNC+Nc125a+inqg=,iv:SxGmWHPiu4+JNRFKwbqi/u/FMqwbY+osbhXTg4nXe60=,tag:wEwU888ufCr0l2aWYNOh9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcXRJa3FQYnhYWVhaaHNu
            T0RaRTV5V0xNVzFSMUNLT2JIU2NRTThRdlhRCnlGdmR0Yk9Db0VLWXVHdDRWOCtD
            ZFRXTnh1VEY5QU1MQStUN1lRNC9qWDgKLS0tIHBqOE1TQmZvbjdObWRnM2JETEJV
            Q0x3WnlNKzUzTU1OTlJyVFphbUxxckkKHBUdNBZ6e927mGpsv53uDviHjP4oxNXp
            rXT+/1bgjOiSz5+xNvf2lY3SVLcLrhRYBTaqhPmTU1mn9yaUZKjJtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T22:11:10Z"
    mac: ENC[AES256_GCM,data:t/edgv5ifvqYPEf6tEQUN5RRywYn0ydsYPacGHN2Jof5eL+MlXa0TLIHp+dXYuKktLhGABj9gmdQIkvgpx08i5Img79RKrfilQyHB5Z+1gLsGPKipU3OgTNjRqdqHac3pCY0niPlQ1VsqAfu5FgTgOOEL3jz7Y4KbYeyn7XSfos=,iv:UjWXFnCCT0vAZjhEtGBckz0HneG4t07ZNNNhuzwWRLc=,tag:T+27E7eI81GEHP/yCacDeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
