apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:RcHX6h6FsWJyju0jH20msq+VjYGFZR2i1nGYop44vvA=,iv:xh091ZmtLQ75UBEtDOTlagO0XvbVqWTPjZAfAgY7elU=,tag:oO+nsO4VijvARKQBjz944g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaUF5em1Bak5SYUk4S09J
            RGFLaVhiWkw5NkpPZGtmSFZWdGl3eEY2WVUwCjdXdkw5cjFiL05aSW9DMjQ2ZUxk
            WE1QSmxmcndjZFAwNittSDhDM1NVQnMKLS0tIHZncGNxTjQ0YnZxWGZ5NksrWW9s
            T3VuWEp3dzlldmozUDJKRHJncjdjUnMKmV/ctIQElO2/w1r6aLO1o1IJ+I/tzWTY
            OtISsHX/aDtKY+XOm83C8cOpjuz5uwTwPxJWg+oO8CGXww6lYSBnGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T16:11:10Z"
    mac: ENC[AES256_GCM,data:xQBblQCu9PincLmusUbUgdY3MJJopgR7scG+PH4SvqfJMZExof6tVk4gqdDdB/GaadgoWpG5tS5QzJ+zNJLfmsXzNax4Q5YmSKPc5YXaNRENgDSKZEYK+BhkVukxWgOw0gtJY/HW5c81w9qsznN2sufBcKyw6edhGMOVZBISTrM=,iv:bpgBWhhiZkbJ9A38ql3q+G6gup8L0HFbHG7+f88O3wQ=,tag:T4o4fB4fTD6XcBeOfF0Oeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
