apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:28adPAy1mfcMyNv18u45FxkAOl1EUr95p/6Rv5YrCEg=,iv:ji5aPQv9++bZQkNtxKphbgVVOr7zq33hfx0DBZgH7nA=,tag:FfH6nK9EwTazyCwJY6ogkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dlEwQ1drV3Q5Z2dqSFZp
            STlFOFRoRmVSUmVuZnhmSXI4RjRhb3BCUWhjCkcra01jM0FTL1F0SXBOclpwWXVJ
            VFQyOWNkVVNITDljMldiOWdzSHZmNlkKLS0tIHdWYWRDTEdhMnF3USt2VUNjMUt3
            dk5rME05MXVocHVER2ViNUpqL285alEKGzG/E1cYrIveFaEOq/8gxInSPfJx4DU7
            iM+quQ1/u+q/LaZqhP+d+xhUNEiYmGFcTp3Ky9VO5HINkFm9rg9B6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T19:32:13Z"
    mac: ENC[AES256_GCM,data:sf3gYJ5sNyq4urIxCPYDa3YjV1vnEcjWeKe7uOfVlWH53HfpeXKQyF1VxNMKChAASZk/SsFPKvhaX37sxLNblUy8054bj8HDF1D7ExHjj3pMv4FEpXhhTmfY0OliM43iMSDeMsAzDCj2/VaaPvgQ2LrGEeApfky/UgMKkOHcVg0=,iv:XG6NjG64x3o3KmFr0uNmBVY8xSskhCV/V33KhW4jRMk=,tag:h4S+pJfX9xRxE1dCo2cDKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
