apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:UJEs0q9OkZWfx9sG2flaYmRHnEszLrHAVVGvqdr7uS8=,iv:uH0ce6vYiKL30U1Mq0HtEj1bVLQBaP8vl2N3/U6E3po=,tag:ieb0Pe9D1m2EjjutlmnWmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTU4xUE9VeUtpeS9pbmhx
            czBoR1lyV1pOcG1LUkRhVmVyemFReEhDMndFCnBvTXp6MlhLV1ZJQitKekNiVm9U
            N3diYzUrOEFhNjk1ZGVFanpReWo0ZU0KLS0tIFg2WjlWeE9zQzh6SFVJa3gvSXVB
            OTkzUk4yRnUyTm85S201OU90b0dzd1UKe9h35nNeKFPH+RZwUQ9ojf31pp8pDUWw
            kdgMg6B80S2Yfqd/wBpIlbZpl2I7lQU0SylMWlwGkpTxWMrKEndGtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T19:11:25Z"
    mac: ENC[AES256_GCM,data:gi4Absx4clIa6hS37X12bfrkFSCo8cgD0HdXy3mcLeAsnGUDJkrt80TCfzq/Il4uSj0UPX5EiqFubW+cigo4dGpuOfykMlpUClHu7wuHEFmQgRn0MSKUPLLtFHJLqgCSvT88I/Yj3yGsEyg9bQ0igpO3Ul7AFXe1zJJ3OMgKlsk=,iv:7966+udmb/ZKd677VTYPTzafgJQEeXOsmgsIp5GGQ3A=,tag:wLRxyT80FrqRgW+1e5Rwow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
