apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:KyuZqQ9z1k6TefmBv6xzumIoJLJsa2e3QeGVj55kJPg=,iv:efy9QP6tCCZWOKm9j9RMBC9p2xe7XYxnJvc7BOy4IIU=,tag:8DN0OFTcX8zmANXUPruBuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ0E2Wk94K3FtUUdRN3dj
            MThueU5QSjNvdUZwSzc2MjlRSjdqaWZYSFFVClZQVXIzNHJYOHNBQmhnTGJ3dWhM
            MGRYbWtEMHBnUDRCam9EaXN4eGxUQVUKLS0tIEtKc1RYYzluVEZ1WVYrd2IraE1j
            Z2EwNTl4OGRlNEU5VGNtNVRzUDFWVEEK2nUyX90TTL7dv3ZfyaXZ7OiSJ3VSb3+S
            yhFzO6heIF9ZarJ1LpV38kqvtCqgBAphYni9/eKAAtbT2ZZ4T0VoCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T02:14:21Z"
    mac: ENC[AES256_GCM,data:zwC8DRlFZcbeZuNYrVQpbOiwxiXM5NCdqAE3gxsPWQAhr2tQJEHKbPLGCGEpgbz4rsUiBCYy0ME53zEdCMhfaT+q++06G2AAl/74p/DvulSVufuSiwF5932Azx01dwHTfCcOuhL79H4oOqlwe6QkDftU9L2zM1PSArOwjNBLJBo=,iv:7JsNBbhp3m3rS2TQLCzvMsKz2cFOF64JP5m8d+4qJtM=,tag:uf4Y0XuaU0nMHAngfrxINg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
