apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:O0qHjbtaXcf/Yr2wuNvpHYkMGf85pePYZGL4+dgyHo8=,iv:M6cye7TKLCAHguXJwE06cTvRJspW7XoxfATHsEoDP4U=,tag:liT88MV655GLgm9G7AwqnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcnBYZXRjMnptOUlxcUt2
            WmltWXZPZktXZ1VpMzl1SW9pTGNUSmFRUWhnCm5aRlJmZkdOZ1M5UEIyRUxVbkhp
            RFRCeWovNFVCSWFrZHlIQ1dCS1luSGMKLS0tIGRJZmxtdDRBa2puSndvVGJkMEFR
            UXlQYkJCSkVCbE5Yc3B0eXljZ3UxSFUKrOLnViKNBs3PUbLY/BKdGTb++qV9qC/c
            co85ZrxlFujn4FvA9deb7L0inf8XXUKO6cDopM6Rv2teUz0qj5ZwXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T22:31:44Z"
    mac: ENC[AES256_GCM,data:RnkXKnbIlo+I/FKT2SD671CaaetatYavQ0M+hahs2exqu8oQQCOmGKdiIOChrQEzqrmQbPcCBHMrk8Ebk0YQkQLRyGRZHsGq+Le4jDbvxhK6348T/PGR8cMjn/NXEUjRqAxRIejaqh8pAj1umR14kP2IkYFynYPNUqRvwMEv3rI=,iv:yQK7mpoFFlZVsD/nIZEBgMK17z8j5Hcskt+9+m4HxMs=,tag:2adFfabG8zvCKWpqIPrEZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
