apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:6GbkeqJ4ekUB6UMl1kbZVpVq1zkMlJb4RjIDRqCANoQ=,iv:NF0AuO5Ae3+KnwbnkVM/yWatfN78GInL2QLyBNxQWWs=,tag:7vMjrVys/SosmsMQePV7Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQVlJN244N2VjaWlvK2NU
            bGlCbFJTK1psazFONmtiVjR3dktwSEZYYXk0CnNKR2RJemR2dWFrRkhYNlc1eWR2
            SXBoeG1tL1VNMFgvQXB1dG5BOUFWRmcKLS0tIDI2VE9BUnpyWTlkaWJ5STBmR1ZZ
            L3FhaE16MkpRZWNiVTNHdzJQY21MSTgK1SpouNaVYPZtNsWGxU0ycwEiw5CZw7a8
            KrkvUGyXk2VkYJQNR1Kzu1qEgOGrbZHPd4po2Jfn2Vk5A4yquKht1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T01:24:07Z"
    mac: ENC[AES256_GCM,data:ucP8GWDdK70Wxqws6Ee3Ah1SxtltqqC2x2c001i5gYoWaQl3ajJ1OpCAlWSJhhr7UUk1bPJxasCFHW7ocQgG2fzshkPOPIJgIITmYCC5d3UpNkVS+CL03vzF6IruH/ayu/OlkGIFGsJ8EoBSwy4ypvzFqeGoZvhAZA0G6apF82M=,iv:0F/DLaNie7KpQg4F9sEvgxfrY/9NY/Z0qStrYbQsSmQ=,tag:K/VEx7tJ+xGjMRrL8znMtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
