---
# yaml-language-server: $schema=https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.6.9-standalone-strict/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
