apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4b8bYDMAV+NtjYVg8em50u94jI6QnXXc9l8IOaM3j+eA20Gj6yePqQ==,iv:DKSyWtqdgZdnlLGuxfhTDzAljj8muteHAhLoviKoKfU=,tag:9qCP+zI+QOa5kHF68By93Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VUluRWJvU1grZURzZ0p6
            VS8vd1o5WU5vUHFXQ1hMMmFhUDIzdmUvMHlBCjUwSzZVazh1NEpIY0RqRnV0UmVp
            Rjc1cWhnR0FwOG1GNHNlUTUxMlRrbGcKLS0tIGNiZ2pZT29aTGVKUzc2WW4ySWFQ
            Yjc0cC9SbUc4anJtWXZ2MFRkWnBTTlkKHIqXfDZL/VH8y9netF7FTqZN7lzZVxSy
            HWiT2DUO3BHNAfHIJFI06bfHPqggHF2k3nv3vCkuCqXRlUqoo2V3Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T00:13:20Z"
    mac: ENC[AES256_GCM,data:uVjToVblYuSHxbXo/Z54n1QlulHv3BmxooRoFHEwfPMAopWNzkOgRWfxgP9XsxeugJSvPXSssBdkNCJcG+MY/8MguRuRPsa6OGpIj/8JQGsV2Znpfac3FGyEyLxl9OQNOEuG90FYiqG5VPFyJ35pnnKgh/vGd/c0jUNq/ZjoqxM=,iv:2Xee3Q2AbVrqfid3U6jULql1Gsm4NZDgXvfSIqKH4gE=,tag:jd6M6Enxfif/rv4k0A/Bgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
