apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ICc55o+d/cVCNmO+O1if2CfHfsLeaY/O6aKQpRyySKBeM6bAaTAWaQ==,iv:SeowK6wDpaoe+QHtjHP+PWo4UB1Qb7D+87zlCPf4n8g=,tag:Rh0eJ12PrRUNLBwpBevWhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ajcxclcwTjZuckNXSDBX
            dGVYMStMU0xxVTJ0MndaUlNROTVkd3R1NDFNCk41VjlTOTJBd3Z1WnBRZGZtbmk4
            bXBvTzJNR0EycFllbEZLMXlHc2tSa1kKLS0tIEFFZWYvWUFFYzlNZzBtRUQ5WGZi
            R29xejNyK3ZScUxZcytvei92K1BNaVUKvH2bQpmoRyMZs6+0unaZFQWBDSbBOM7K
            h8147P/9zDais+iqp0OO/REVf3P7hLVI/ZTvJI5LJiIJ1ZIe37VWzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T19:19:00Z"
    mac: ENC[AES256_GCM,data:VgO30/Uw60pJ0Cp8XE4jesIlEjjP+Fu1yyLGxzSqmyEMBfibRnmUp/RzJ6PZXzAN/ooSoJrD8Jnc6f8vyhFeg8agT1hm0YiWVCTAIATnefdCm9rBgb9FnKIOm4ZAbNm2UszIG7zzyrnEK7FmtLJ0FuHcgvfz/CFHi53BtUCsSck=,iv:f8FsWzcZWu6Wr37pe3z3Ycbv0wafY6VRrQULp4+BEss=,tag:RHO99idUvhn1QhySWomfzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
