apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4vHCxJjrHWvM/RcQRnByVSZqBdEtIUA+gIekYqL2hMMZ9QD1zp9afQ==,iv:gY4kq2uzWtbZFJKL7OgdJ0qMJiyBsgwnx9kmmG6R8k0=,tag:YB6UeXpq5qF+o3tSPLimtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f5fdfude93x5xl63au2w8paa3qtcq98asy3n6h79lkwwp5hlhu2qg8l7e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieDVoWXo3R1F4MTJnaXlq
            MzU4Y3dod0RPRUJ0SmVON0JqZElxSGgza1Q4CmFXL1JxNjRCdXo4M2JqbUtWQjEv
            ZkNlMDRMYUpuSUF4dG1VdUwxTmNMbFUKLS0tIDdodzJUZ2RLUFJQS3krVkE3a0RR
            WU1vTnNIRWVEY1Z6VSs1aEY5d2Y1UU0KlH799NXCI7IzIy03BaW+nji0gNSDCidO
            qtX7G7ZxIAfaSa+C2SnZ1SFoFwO4rOK/B5/GyNJ3e5GG5lkyTw/Bbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T02:14:21Z"
    mac: ENC[AES256_GCM,data:Dt+ugGFSdNNBfftEaE3i5/HP29HYcCE2Rb4LiCPolwcWqivXM+VcTBP/zBd3j+ibX8W5PGjZ2a9NXEF1GqwMuM3ocvp1yzOz1hQcVmKP6gKwsU4CrSRP0yRh918rqBXb5Jjt1nImUzRAwdZnXrhsWDO73gmkZvoQardX/6UclCk=,iv:Q9kgxHJ04rEYnIx8evuNkduLrDvK14u3Wi04gJGy2XQ=,tag:eqejr3dUyu6JHCSEvO+K6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
