mqtt:
  host: 192.168.2.15
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  global_args: [-hide_banner, -loglevel, warning]
  hwaccel_args: -c:v h264_qsv
  output_args:
    record: preset-record-generic-audio-aac

cameras:
  garage_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@192.168.2.138:554/h264Preview_01_main
          roles:
            - rtmp
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@192.168.2.138:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
      stationary:
        interval: 5

  porch_camera:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac
        rtmp: -c:v copy -f flv -ar 44100 -c:a aac
      inputs:
        - path: rtsp://192.168.2.31:554/s0
          roles:
            - record
        - path: rtsp://192.168.2.31:554/s2
          roles:
            - detect
    record:
      enabled: True
    detect:
      width: 1024
      height: 576
      fps: 5
      stationary:
        interval: 5
    motion:
      mask:
        - 0,0,227,0,239,35,271,160,447,159,680,177,1024,295,1024,0,396,0,305,0,195,0,190,21,0,21
        - 262,576,249,342,298,309,343,293,362,329,454,576
    objects:
      filters:
        person:
          mask:
            - 165,576,169,0,827,0,832,105,279,169,274,250,326,265,343,293,362,329,454,576

record:
  enabled: False

objects:
  track:
    - person
