mqtt:
  host: 192.168.2.15
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  hwaccel_args: preset-intel-qsv-h264

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 2

record:
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 2
      mode: active_objects

objects:
  track: [person]

go2rtc:
  streams:
    porch_lq:
      - rtsp://192.168.2.31:554/s2
      - "ffmpeg:porch_lq#video=h264#audio=aac"

cameras:
  garage_camera:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@192.168.2.138:554/h264Preview_01_main
          roles:
            - rtmp
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@192.168.2.138:554/h264Preview_01_sub
          roles:
            - detect
    record:
      enabled: False
    snapshots:
      enabled: False
    detect:
      width: 1024
      height: 576
      fps: 5
      stationary:
        interval: 5

  porch_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/porch_lq
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/porch_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
      stationary:
        interval: 5
    motion:
      mask:
        - 0,0,227,0,239,35,271,160,447,159,680,177,1024,295,1024,0,396,0,305,0,195,0,190,21,0,21
        - 262,576,249,342,298,309,343,293,362,329,454,576
    objects:
      filters:
        person:
          mask:
            - 165,576,169,0,827,0,832,105,279,169,274,250,326,265,343,293,362,329,454,576
