---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: linkwarden-secret
    template:
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: linkwarden
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .LINKWARDEN__POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LINKWARDEN__POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        DATABASE_URL: "postgresql://{{ .LINKWARDEN__POSTGRES_USER }}:{{ .LINKWARDEN__POSTGRES_PASSWORD }}@postgres16-rw.database.svc.cluster.local:5432/linkwarden"
        # Auth
        NEXTAUTH_SECRET: "{{ .LINKWARDEN__NEXTAUTH_SECRET }}"
        AUTHENTIK_CLIENT_ID: "{{ .LINKWARDEN__OAUTH_CLIENT_ID }}"
        AUTHENTIK_CLIENT_SECRET: "{{ .LINKWARDEN__OAUTH_CLIENT_SECRET }}"
        AUTHENTIK_ISSUER: "{{ .LINKWARDEN__OAUTH_ISSUER }}"
  dataFrom:
    - extract:
        key: linkwarden
    - extract:
        key: cloudnative-pg
