---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocis
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ocis-secret
    template:
      engineVersion: v2
      data:
        OCIS_JWT_SECRET: "{{ .OCIS_JWT_SECRET }}"
        # OCIS_OIDC_ISSUER: "{{ .OCIS_OIDC_ISSUER }}"
        # OCIS_OIDC_CLIENT_ID: "{{ .OCIS_OIDC_CLIENT_ID }}"
        # WEB_OIDC_POST_LOGOUT_REDIRECT_URI: "{{ .WEB_OIDC_POST_LOGOUT_REDIRECT_URI }}"
        # OCIS_OIDC_METADATA_URL: "{{ .WEB_OIDC_METADATA_URL }}"
        # WEB_OIDC_METADATA_URL: "{{ .WEB_OIDC_METADATA_URL }}"
        # OCIS_ADMIN_USER_ID: "{{ .OCIS_ADMIN_USER_ID }}"
  dataFrom:
    - extract:
        key: ocis
